FROM stanfordoval/genienlp

MAINTAINER Thingpedia Admins <thingpedia-admins@lists.stanford.edu>

# Use root for now until https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8 is fixed.
# There is a workaround by changing pod fsgroup but kfserving inference service cannot set pod level security context.
USER root

RUN pip3 install awscli

WORKDIR /home/genienlp
ENTRYPOINT ["/opt/genienlp/dockerfiles/kfserver_start.sh"]
