#!/bin/bash

set -e
set -x
echo "Running in $(pwd)"

version=$(git describe)

case $IMAGE_NAME in
	*-cuda)
		version=${version}-cuda
	;;
esac
docker tag $IMAGE_NAME $DOCKER_REPO:$version
docker push $DOCKER_REPO:$version
